[package]
name = "wyrm"
version = "0.1.0"
edition = "2021"

[profile.dev]
opt-level = 3

[dependencies]
log = "0.4"
env_logger = "0.10"
fastrand = "1.7.0"
image = "0.24"
rayon = "1.5"
indicatif = "0.16"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "render"
harness = false

